In [12]:
import numpy as np
m=np.array([1,2,3,4,5,6,7,8,9])
slice1=m[2:6]
print(slice1)

[3 4 5 6]


In [5]:
slice2=m[::2]
print(slice2)

[1 3 5 7 9]


In [7]:
slice3=m[::3]
print(slice3)

[1 4 7]


In [9]:
reversed_arr=m[::-1]
print(reversed_arr)

[9 8 7 6 5 4 3 2 1]


In [10]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=m[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [15]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=m[:2,:3]
print(subarray)

[[1 2 3]
 [4 5 6]]


In [23]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
col1=m[:,0]
print(col1)

[1 4 7]


In [26]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
row1=m[0,:]
print(row1)

[1 2 3]


In [28]:
print(m[0:2:1])

[[1 2 3]
 [4 5 6]]


In [37]:
import numpy as np
import array
m=array.array('i',[10,20,30,40,50,60])
print(arr[4])
print(arr[2])

50
30


In [49]:
import numpy as np
import array
m=np.array([[1,2,3],[4,5,6]])
print(m[0,0])
print(m[1,2])

1
6


In [54]:
m=[10,20,30,40,50,60,70]
print(m[1])

20


In [52]:
print(m[-1])

70


In [53]:
print(m[1:4])

[20, 30, 40]


In [60]:
m=np.array([10,20,30,40,50])
print(m[arr>20])



TypeError: '>' not supported between instances of 'array.array' and 'int'

In [61]:
print(arr[(1,3)])

TypeError: array indices must be integers

In [1]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [2]:
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
result=np.array_split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.array_split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
