In [2]:
import numpy as np
a=[20,40,50,70,10]
b=[6,2,9,7,1]
m=np.array(a)
k=np.array(b)
print(m)
print(k)
print(m+k)
print(m-k)
print(m*k)
print(m/k)

[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]


In [5]:
print(m.dot(k))
sclr=3
print("scalar value:",sclr)
print("array:",m)
print("result:",m*sclr)
      

1150
scalar value: 3
array: [20 40 50 70 10]
result: [ 60 120 150 210  30]


In [6]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [11]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[10,7,2]
arr2=[6,5,3]
vect_func=np.vectorize(my_func)
print("array 1:",arr1)
print("array 2:",arr2)
print("result:",vect_func(arr1,arr2))

array 1: [10, 7, 2]
array 2: [6, 5, 3]
result: [4 2 5]
