In [3]:
import numpy as np
a=np.random.random((3,4))
print("\n Random Values :\n",a)


 Random Values :
 [[0.75686491 0.38155596 0.83339695 0.19754408]
 [0.6779637  0.02613233 0.66904946 0.76272944]
 [0.17548205 0.46815731 0.34557373 0.26233129]]


In [6]:
a=np.zeros((3,4))
print("\n Array with all Zeros:\n",a)


 Array with all Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
m=np.array([[10,20,30],[40,50,60]])
print("\n Shape of array :\n",m.shape)
print("\n No of Dimensions :\n",m.ndim)
print("\n Element type:\n",m.dtype)


 Shape of array :
 (2, 3)

 No of Dimensions :
 2

 Element type:
 int64


In [10]:
flat=m.flatten()
print("\n Flattened Array \n",flat)


 Flattened Array 
 [10 20 30 40 50 60]
