In [1]:
import numpy as np
a=np.array([1,2,3,4])
print("\n one dimensional array \n",a)


 one dimensional array 
 [1 2 3 4]


In [2]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print("\n two dimensional array \n",a)


 two dimensional array 
 [[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n three dimensional array \n",a)


 three dimensional array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
import numpy as np
a=np.zeros((2,3))
print("\n value with all zeros \n",a)


 value with all zeros 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import numpy as np
a=np.arange(8,29,3)
print("\n sequence array \n",a)


 sequence array 
 [ 8 11 14 17 20 23 26]


In [8]:
import numpy as np
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=m.reshape(4,3)
print("\n original array \n",m)
print("\n reshaped array \n",newarr)


 original array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
import numpy as np
a=np.random.random((2,3))
print("\n random value \n",a)


 random value 
 [[0.81146573 0.71433139 0.35010373]
 [0.95278343 0.38127397 0.33656372]]


In [8]:
import numpy as np
m=np.array([[1,2,3,4],[5,6,7,8]])
flat=m.flatten()
print("\n original array \n",m)
print("\n flattened array \n",flat)


 original array 
 [[1 2 3 4]
 [5 6 7 8]]

 flattened array 
 [1 2 3 4 5 6 7 8]


In [16]:
import numpy as np
m=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\n no of dimensions \n",m.ndim)


 no of dimensions 
 3


In [17]:
import numpy as np
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n shape of array \n",m.shape)


 shape of array 
 (3, 4)


In [18]:
import numpy as np
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n element type \n",m.dtype)


 element type 
 int64


In [19]:
import numpy as np
m=np.array([[1,2,3],[4,5,6]])
size=len(m)
print("\n size of array \n",m.size)


 size of array 
 6
